name: CI

on:
  push:
    branches:
      - feature/ota-updates

env:
  cargo_file_path: ./Cargo.toml
  wifi_ssid: ${{ secrets.RUST_ESP32_STD_DEMO_WIFI_SSID }}
  wifi_password: ${{ secrets.RUST_ESP32_STD_DEMO_WIFI_PASS }}

jobs:
  compile:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - uses: ./.github/actions/esp-build