name: CI

on:
  push:
    branches:
      - ci

jobs:
  compile:
    name: Build
    runs-on: ubuntu-latest
    container: espressif/idf-rust-examples
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - uses: fregante/setup-git-user@v1.0.1
      - name: Cargo | Get version
        id: cargo-get-version
        uses: "bakery/actions-cargo-get-version@v1"
      - name: Debug | Show version
        run: echo "Detected version is ${{ steps.cargo-get-version.outputs.version }}"
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}
      - name: Save Run ID
        run: echo "${{ github.run_id }}" >> version-data.txt
      - name: Add and commit
        run: git add version-data.txt
      - name: Add and commit
        run: git commit -m "update build number to ${{ github.run_id }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Configure | Esp toolchain
        run: rustup default esp
      - name: Build | Cargo
        run: export RUST_ESP32_STD_DEMO_WIFI_SSID=ssid; export RUST_ESP32_STD_DEMO_WIFI_PASS=pass; cargo espflash save-image firmware.bin
      - name: Debug | Show and tell
        run: ls -al
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Test firmware build"
          files: |
            firmware.bin
