name: CI

on:
  push:
    branches:
      - ci

# env:
#   rust_toolchain: nightly-x86_64-unknown-linux-gnu
#   esp_rust_toolchain: https://raw.githubusercontent.com/esp-rs/rust-build/main/install-rust-toolchain.sh

jobs:
  compile:
    name: Build
    runs-on: ubuntu-latest
    container: espressif/idf-rust-examples
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Configure | Esp toolchain
        run: rustup default esp
      - name: Build | Cargo
        run: export RUST_ESP32_STD_DEMO_WIFI_SSID=ssid; export RUST_ESP32_STD_DEMO_WIFI_PASS=pass; cargo espflash save-image firmware.bin
      - name: Debug | Show and tell
        run: ls -al
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Test firmware build"
          files: |
            firmware.bin
