name: 'Container Action Template'
description: 'Get started with Container actions'
author: 'GitHub'
inputs: 
  command:
    description: 'Command to run'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
