name: "Container Action Template"
description: "Get started with Container actions"
author: "GitHub"
inputs:
  command:
    required: true
    description: "Command to run"
runs:
  using: "docker"
  image: "Dockerfile.esp32"
  args:
    - ${{ inputs.command }}
